appium.server.url=http://127.0.0.1:4723

platform.name=Android
automation.name=UiAutomator2
device.udid=863d0058304830363451092b8d7ccb
new.command.timeout.seconds=60
wait.timeout.seconds=10

app.package=com.android.contacts
app.activity=com.android.contacts.activities.PeopleActivity
